repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: python -m black
        language: system
        types: [python]

    -   id: isort
        name: isort
        entry: isort --profile black
        language: system
        types: [python]

    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
