services:
  api:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      - ai_network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2", "--timeout-keep-alive", "4000", "--reload"]
    working_dir: /app
    environment:
      - PYTHONPATH=/app

networks:
  ai_network:
    driver: bridge
