services:
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ai_network
    command: redis-server --appendonly yes

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    networks:
      - ai_network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2", "--timeout-keep-alive", "4000", "--reload"]
    working_dir: /app/api
    environment:
      - PYTHONPATH=/app:/app/api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

networks:
  ai_network:
    driver: bridge
