# Use the same base image as your FastAPI app
FROM python:3.9

# Set the working directory
WORKDIR /app


COPY ./ /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir celery


# Copy the actual application code
COPY . .

# Set environment variables for Celery
ENV PYTHONPATH=/app
ENV CELERY_BROKER_URL=redis://redis:6379/0
ENV CELERY_RESULT_BACKEND=redis://redis:6379/0

# Command for Celery workers
CMD ["celery", "-A", "celery.celery_app", "worker", "--loglevel=info", "-c", "4"]
