services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    networks:
      - ai_network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2", "--timeout-keep-alive", "4000", "--reload"]
    working_dir: /app/api
    environment:
      - PYTHONPATH=/app:/app/api
      - PYMOL_HEADLESS=1
      - PYMOL_QUIET=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}

networks:
  ai_network:
    driver: bridge
