name = "sci-vis-ai-server"
main = "worker.py"
compatibility_date = "2024-03-20"
compatibility_flags = ["python_workers"]

[build]
command = "pip install --no-deps -r requirements.txt"

[vars]
# These are non-sensitive default values that can be committed to git
# For Celery worker connection (will need adjustment for Workers environment)
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"

# If you have development/testing API keys that are not sensitive:
# OPENAI_API_KEY = "your-development-key"
# ANTHROPIC_API_KEY = "your-development-key"
# GROQ_API_KEY = "your-development-key"

[env.production]
routes = [
  { pattern = "sci-vis-ai-server.jakekinchen.workers.dev", custom_domain = true }
]

# SENSITIVE ENVIRONMENT VARIABLES
# The following sensitive variables must be set using the Cloudflare dashboard or wrangler CLI:
# 
# npx wrangler secret put OPENAI_API_KEY
# npx wrangler secret put ANTHROPIC_API_KEY
# npx wrangler secret put GROQ_API_KEY
#
# For production Celery settings (if different from defaults):
# npx wrangler secret put CELERY_BROKER_URL
# npx wrangler secret put CELERY_RESULT_BACKEND