name: Disk Space Monitor

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  monitor-disk-space:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Check Server Disk Space
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Get disk usage
          USAGE=$(df / | awk 'NR==2 {print $5}' | sed 's/%//')
          FREE_GB=$(df / | awk 'NR==2 {printf "%.1f", $4/1024/1024}')
          
          echo "Current disk usage: ${USAGE}% (${FREE_GB}GB free)"
          
          # Alert if usage is high
          if [ "$USAGE" -gt 85 ]; then
            echo "::warning::High disk usage detected: ${USAGE}%"
            
            # Run cleanup if available
            if [ -f "/opt/hackathon-server/sci-vis-ai-server/scripts/maintenance/docker-cleanup.sh" ]; then
              echo "Running automated cleanup..."
              /opt/hackathon-server/sci-vis-ai-server/scripts/maintenance/docker-cleanup.sh --threshold=80
            fi
          fi
          
          # Fail the job if critically low
          if [ "$USAGE" -gt 95 ]; then
            echo "::error::Critical disk usage: ${USAGE}%"
            exit 1
          fi

  cleanup-old-artifacts:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Cleanup Old Docker Images
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Clean up Docker artifacts older than 7 days
          docker image prune -a -f --filter "until=168h" || true
          docker container prune -f --filter "until=168h" || true
          docker volume prune -f || true
          docker network prune -f || true
          
          echo "Docker cleanup completed"